In [ ]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import scipy as sp

Numpy merupakan library Python yang fokus pada scientific computing,simpelnyamenyediakan fungsi yang siap pakai untuk memudahkan kita melakukan perhitungan saintifik seperti matriks, aljabar, statistik, dan sebagainya.
Pandas adalah library open source Python yang berfungsi untuk pengolahan data.
Seaborn merupakan library untuk membuat grafik dan statistik dengan menggunakan Python.
Scipy merupakan adalah suatu modul untuk melakukan beberapa perhitungan scientific dengan aplikasi python. Sedikit contohnya adalah integral numerik.

In [ ]:
dataset = pd.read_csv('mlbb_hero1.csv', sep=";")
dataset .head(5)

hero_name      role  defense_overall  offense_overall  skill_effect_overall  \
0   Terizla   fighter              7.0              8.0                   6.0   
1    Martis   fighter              6.0              8.0                   5.0   
2     Grock      tank              8.0              5.0                   6.0   
3  Carmilla   support              5.0              5.0                   9.0   
4   Irithel  marksman              5.0              5.0                   8.0   

   difficulty_overall  movement_spd  magic_defense  mana  hp_regen  \
0                 6.0           255             10   430        54   
1                 5.0           260             10     0        35   
2                 4.0           260             10   430        42   
3                 5.0           255             10   430        39   
4                 7.0           260             10   438        35   

   physical_atk  physical_defense    hp  attack_speed  mana_regen  win_rate  \
0           129                19  2728          0.80        21.0     47.00   
1           128                25  2738          0.86         0.0     45.00   
2           135                21  2819          0.81        12.0     47.69   
3           126                25  2528          0.91        16.0     53.76   
4           118                17  2540          0.82        15.0     51.52   

   pick_rate  ban_rate  release_year  
0       0.15      0.02          2019  
1       0.15      0.02          2018  
2       0.14      0.02          2017  
3       0.08      0.02          2020  
4       0.38      0.03          2017

Melihat 5 data teratas dari data mlbb_hero1.csv

In [ ]:
dataset.tail()

hero_name      role  defense_overall  offense_overall  \
98   Esmeralda      mage              7.0              6.0   
99   Benedetta  assassin              5.0              6.0   
100      Brody  marksman              6.0              9.0   
101    Natalia  assassin              6.0              9.0   
102   Silvanna   fighter              6.0              6.0   

     skill_effect_overall  difficulty_overall  movement_spd  magic_defense  \
98                    6.0                 4.0           240             10   
99                    7.0                 7.0           260             10   
100                   4.0                 7.0           253             10   
101                   4.0                 6.0           250             10   
102                   5.0                 4.0           255             10   

     mana  hp_regen  physical_atk  physical_defense    hp  attack_speed  \
98    502        36           114                21  2573          0.80   
99    460        33           128                15  2499          0.88   
100   435        36           140                14  2490          0.96   
101   486        35           121                18  2589          0.89   
102   430        39           126                22  2828          0.91   

     mana_regen  win_rate  pick_rate  ban_rate  release_year  
98         20.0     49.14       1.25     42.29          2019  
99         16.0     52.38       0.72     49.46          2020  
100         3.0     51.57       0.71     60.05          2020  
101        15.0     47.76       0.41     61.29          2016  
102        16.0     52.65       3.06      9.59          2019

Melihat 5 data terakhir dari data mlbb_hero1.csv

In [ ]:
dataset.dtypes

hero_name                object
role                     object
defense_overall         float64
offense_overall         float64
skill_effect_overall    float64
difficulty_overall      float64
movement_spd              int64
magic_defense             int64
mana                      int64
hp_regen                  int64
physical_atk              int64
physical_defense          int64
hp                        int64
attack_speed            float64
mana_regen              float64
win_rate                float64
pick_rate               float64
ban_rate                float64
release_year              int64
dtype: object

In [ ]:
dataset.describe().transpose()

count         mean         std      min      25%  \
defense_overall       103.0     5.786408    1.672444     2.00     4.50   
offense_overall       103.0     6.378641    1.771875     4.00     5.00   
skill_effect_overall  103.0     6.456311    1.538886     4.00     5.00   
difficulty_overall    103.0     5.922330    1.649060     3.00     5.00   
movement_spd          103.0   251.048544    9.261324   230.00   240.00   
magic_defense         103.0     9.611650    1.941462     0.00    10.00   
mana                  103.0   358.844660  217.446805     0.00   385.00   
hp_regen              103.0    37.961165    7.818934    19.00    34.00   
physical_atk          103.0   117.504854    8.451562    97.00   112.00   
physical_defense      103.0    19.135922    3.865505     2.00    17.00   
hp                    103.0  2585.932039  227.274528  1138.00  2500.50   
attack_speed          103.0     0.836505    0.046415     0.73     0.80   
mana_regen            103.0    12.953398    8.655054     0.00     6.60   
win_rate              103.0    50.183398    2.341717    45.00    48.50   
pick_rate             103.0     0.971068    0.794118     0.05     0.35   
ban_rate              103.0     4.461262   11.575990     0.02     0.08   
release_year          103.0  2017.660194    1.397150  2016.00  2016.00   

                          50%       75%      max  
defense_overall          6.00     7.000     9.00  
offense_overall          6.00     8.000    10.00  
skill_effect_overall     6.00     8.000     9.00  
difficulty_overall       6.00     7.000    10.00  
movement_spd           250.00   260.000   270.00  
magic_defense           10.00    10.000    10.00  
mana                   438.00   490.000  1150.00  
hp_regen                36.00    40.000    92.00  
physical_atk           117.00   123.000   140.00  
physical_defense        19.00    22.000    27.00  
hp                    2578.00  2718.500  3309.00  
attack_speed             0.82     0.860     0.98  
mana_regen              15.00    18.000    50.00  
win_rate                50.10    51.745    56.49  
pick_rate                0.75     1.430     3.71  
ban_rate                 0.36     2.280    61.29  
release_year          2017.00  2019.000  2021.00

Melakukan transpose data untuk type data integer 

In [ ]:
sns.countplot(dataset['hp']).set_title('Presntase Data Draf_Pick')
plt.show()

In [61]:
dataset = pd.read_csv('mlbb_hero1.csv', sep=";")
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -18].values

In [ ]:
print(x)

[['Terizla' 'fighter' 7.0 ... 47.0 0.15 0.02]
 ['Martis' 'fighter' 6.0 ... 45.0 0.15 0.02]
 ['Grock' 'tank' 8.0 ... 47.69 0.14 0.02]
 ...
 ['Brody' 'marksman' 6.0 ... 51.57 0.71 60.05]
 ['Natalia' 'assassin' 6.0 ... 47.76 0.41 61.29]
 ['Silvanna' 'fighter' 6.0 ... 52.65 3.06 9.59]]


Tidak ada data yang kosong 

In [62]:
print(y)

['fighter' 'fighter' 'tank' 'support' 'marksman' 'fighter' 'fighter'
 'mage' 'mage' 'fighter' 'fighter' 'marksman' 'mage' 'marksman' 'fighter'
 'tank' 'tank' 'tank' 'marksman' 'fighter' 'mage' 'fighter' 'fighter'
 'support' 'tank' 'marksman' 'mage' 'mage' 'fighter' 'tank' 'mage' 'tank'
 'fighter' 'fighter' 'marksman' 'mage' 'support' 'marksman' 'fighter'
 'fighter' 'fighter' 'fighter' 'fighter' 'mage' 'mage' 'marksman'
 'support' 'fighter' 'mage' 'support' 'mage' 'mage' 'marksman' 'marksman'
 'tank' 'fighter' 'marksman' 'tank' 'tank' 'mage' 'fighter' 'assassin'
 'marksman' 'mage' 'fighter' 'mage' 'marksman' 'tank' 'mage' 'fighter'
 'marksman' 'support' 'tank' 'mage' 'assassin' 'fighter' 'fighter'
 'fighter' 'assassin' 'assassin' 'fighter' 'mage' 'mage' 'tank' 'assassin'
 'tank' 'assassin' 'fighter' 'marksman' 'assassin' 'mage' 'assassin'
 'support' 'tank' 'assassin' 'mage' 'support' 'assassin' 'mage' 'assassin'
 'marksman' 'assassin' 'fighter']


In [58]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

Mengubah data atribut menjadi numerik dan matriks

In [60]:
print (x)

[[0.0 1.0 0.0 ... 47.0 0.15 0.02]
 [0.0 1.0 0.0 ... 45.0 0.15 0.02]
 [0.0 0.0 0.0 ... 47.69 0.14 0.02]
 ...
 [0.0 0.0 0.0 ... 51.57 0.71 60.05]
 [1.0 0.0 0.0 ... 47.76 0.41 61.29]
 [0.0 1.0 0.0 ... 52.65 3.06 9.59]]


In [63]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

Mengubah data label menjadi data numerik dan matriks

In [64]:
print(y)

[1 1 5 4 3 1 1 2 2 1 1 3 2 3 1 5 5 5 3 1 2 1 1 4 5 3 2 2 1 5 2 5 1 1 3 2 4
 3 1 1 1 1 1 2 2 3 4 1 2 4 2 2 3 3 5 1 3 5 5 2 1 0 3 2 1 2 3 5 2 1 3 4 5 2
 0 1 1 1 0 0 1 2 2 5 0 5 0 1 3 0 2 0 4 5 0 2 4 0 2 0 3 0 1]


In [65]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

Membagi dataset ke dalam training set dan test set

In [66]:

print(x_train)


[['Vale' 'mage' 4.0 ... 51.73 1.88 2.24]
 ['Zhask' 'mage' 5.0 ... 52.74 0.79 2.32]
 ['Bane' 'fighter' 6.0 ... 47.66 0.13 0.1]
 ...
 ['Atlas' 'tank' 8.0 ... 51.58 0.75 1.53]
 ['Vexana' 'mage' 4.0 ... 50.47 0.1 0.04]
 ['Popol and Kupa' 'marksman' 3.0 ... 49.4 0.32 0.12]]


In [67]:
print(x_test)

[['Yi Sun Shin' 'marksman' 4.0 7.0 7.0 6.0 250 10 438 36 124 18 2520 0.85
  15.0 55.32 1.19 0.75]
 ['Lapu Lapu' 'fighter' 5.0 7.0 6.0 5.0 260 10 0 35 119 21 2628 0.9 16.0
  49.13 0.76 0.15]
 ['Badang' 'fighter' 6.0 8.0 5.0 6.0 255 10 0 40 119 23 2708 0.9 0.0
  49.78 1.06 0.14]
 ['Balmond' 'fighter' 7.0 6.0 4.0 3.0 260 10 0 47 119 25 2836 0.85 0.0
  46.3 1.96 1.22]
 ['Silvanna' 'fighter' 6.0 6.0 5.0 4.0 255 10 430 39 126 22 2828 0.91
  16.0 52.65 3.06 9.59]
 ['Argus' 'fighter' 5.0 8.0 7.0 5.0 260 10 0 40 124 21 2628 0.91 0.0
  54.26 0.41 0.13]
 ['Eudora' 'mage' 4.0 5.0 9.0 4.0 250 10 468 38 112 19 2254 0.8 16.0
  48.76 1.69 0.36]
 ['Khufra' 'tank' 7.0 5.0 6.0 5.0 255 10 460 47 117 19 2859 0.78 15.0
  51.46 0.98 2.76]
 ["Chang'e" 'mage' 4.0 4.0 9.0 7.0 240 10 505 34 115 16 2301 0.8 21.0
  52.9 2.07 0.93]
 ['Barats' 'tank' 7.0 6.0 5.0 3.0 268 10 430 42 135 25 2709 0.81 3.0
  46.12 0.1 0.42]
 ['Fanny' 'assassin' 6.0 9.0 5.0 10.0 265 0 0 33 126 19 2526 0.89 0.0
  49.05 0.92 4.48]
 ['Paquito

In [68]:
print(y_train)

[2 2 1 3 5 1 3 2 1 5 4 4 1 2 1 2 1 2 2 3 4 4 3 0 5 3 5 0 1 3 0 3 2 0 2 0 5
 3 2 3 4 1 2 4 2 1 0 2 1 1 5 5 1 0 2 2 0 3 2 3 1 5 1 3 0 3 2 2 3 1 4 1 1 5
 1 0 1 1 1 5 2 3]


In [69]:
print(y_test)

[3 1 1 1 1 1 2 5 2 5 0 1 2 2 1 1 4 5 5 0 5]


In [73]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] =sc.transform(x_test[:, 3:])

Feature Scaling pada kasus ini menggunakan standardscalling

In [74]:
print(x_train)

[['Vale' 'mage' 4.0 ... 0.7103034066314153 1.2907445692468358
  -0.19423985121257836]
 ['Zhask' 'mage' 5.0 ... 1.1497068136915753 -0.16756347776722283
  -0.1876005565900559]
 ['Bane' 'fighter' 6.0 ... -1.0603618079575374 -1.0505756897206897
  -0.3718409823650547]
 ...
 ['Atlas' 'tank' 8.0 ... 0.6450454748898083 -0.2210793694007663
  -0.2531635909874653]
 ['Vexana' 'mage' 4.0 ... 0.16213678000191248 -1.0907126084458474
  -0.3768204533319465]
 ['Popol and Kupa' 'marksman' 3.0 ... -0.3033697997548885
  -0.7963752044613582 -0.37018115870942403]]


In [75]:
print(x_test)

[['Yi Sun Shin' 'marksman' 4.0 0.3179714534068656 0.30419588121565244
  0.007789475583030328 -0.02022156599783919 0.15811388300841892
  0.2785435567675961 -0.16305728593209232 0.8000650308012699
  -0.1670426237628095 -0.18970979390079615 0.3503078091451305
  0.14507452377957247 2.2721432396472254 0.3675954385682115
  -0.3178967135570595]
 ['Lapu Lapu' 'fighter' 5.0 0.3179714534068656 -0.33539545877623217
  -0.6309475222254535 1.085224041884037 0.15811388300841892
  -1.7991657651150592 -0.2880170751510789 0.2315612827449083
  0.5939293289344335 0.27337453211503915 1.4723875103131296
  0.26079544741697464 -0.4208340768897804 -0.20770039649238045
  -0.3676914232259781]
 ['Badang' 'fighter' 6.0 0.861172686310261 -0.9749867987681168
  0.007789475583030328 0.532501237943099 0.15811388300841892
  -1.7991657651150592 0.3367818709438541 0.2315612827449083
  1.1012439640659288 0.6163999587934357 1.4723875103131296
  -1.5907393307814597 -0.13804970600948144 0.1936687907591954
  -0.368521335053793